#!/usr/bin/env python3
"""Fetch generated artwork by URL and put it where the app looks for it.

Pictures are generated by hand, in a tool with a chat window, and they come back as
URLs on somebody's CDN. Getting them into the repository is the boring half, and doing
it by hand is how a file ends up with the wrong name in the wrong folder.

So `art-source/generated.json` is a plain list of what was generated and where it
belongs, and this fetches whatever is missing:

    {
      "content/en/illustrations/fox_mitten_1.png": "https://.../abc.png",
      "art-source/dog-raw/dog_blink.png":          "https://.../def.png"
    }

Resumable and idempotent, like `generate_voice.py` and for the same reason: a list of
six hundred downloads is not something to start over because the network blinked. A
file already on disk is left alone, so re-running is free and safe.

    python3 tools/fetch_art.py --dry-run   # what is missing
    python3 tools/fetch_art.py             # fetch it

It refuses anything that is not actually an image. A CDN that has forgotten a file
answers with an HTML error page and HTTP 200, and an HTML file saved as `.png` is a
broken picture that every later step treats as real.
"""

import argparse
import json
import os
import sys
import urllib.error
import urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MANIFEST = os.path.join(ROOT, "art-source", "generated.json")

# What a real picture starts with. Checked on the bytes rather than trusting the
# extension or the content type, both of which a CDN will happily get wrong.
MAGIC = {
    b"\x89PNG\r\n\x1a\n": "png",
    b"\xff\xd8\xff": "jpg",
    b"RIFF": "webp",          # RIFF....WEBP
}


def looks_like_an_image(data):
    return any(data.startswith(m) for m in MAGIC)


def load_manifest(path):
    if not os.path.exists(path):
        raise SystemExit(f"no manifest at {os.path.relpath(path, ROOT)}")
    with open(path, encoding="utf-8") as f:
        manifest = json.load(f)

    for target in manifest:
        # A manifest is written by hand and lands in a repository. Nothing in it may
        # point outside the repository.
        full = os.path.normpath(os.path.join(ROOT, target))
        if not full.startswith(ROOT + os.sep):
            raise SystemExit(f"{target} is outside the repository")
    return manifest


def fetch(url, retries=4):
    for attempt in range(retries):
        try:
            request = urllib.request.Request(url, headers={"User-Agent": "little-owl/1.0"})
            with urllib.request.urlopen(request, timeout=120) as response:
                return response.read()
        except urllib.error.HTTPError as error:
            # 404 and 403 will not get better by asking again; a CDN's 5xx might.
            if error.code not in (429, 500, 502, 503, 504) or attempt == retries - 1:
                raise SystemExit(f"{url}\n  answered {error.code}")
        except urllib.error.URLError as error:
            if attempt == retries - 1:
                raise SystemExit(f"{url}\n  could not be reached: {error}")
        import time
        time.sleep(2 ** attempt)
    raise SystemExit("unreachable")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--manifest", default=MANIFEST)
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    manifest = load_manifest(args.manifest)
    missing = {t: u for t, u in manifest.items()
               if not os.path.exists(os.path.join(ROOT, t))}

    print(f"{len(manifest)} pictures listed, {len(manifest) - len(missing)} already here")
    print(f"to fetch: {len(missing)}")

    if args.dry_run:
        for target in sorted(missing):
            print(f"  {target}")
        return 0
    if not missing:
        print("nothing to do")
        return 0

    for index, target in enumerate(sorted(missing), 1):
        data = fetch(manifest[target])
        if not looks_like_an_image(data):
            # Almost always a CDN error page served with a 200.
            head = data[:60].decode("utf-8", "replace").replace("\n", " ")
            raise SystemExit(f"{target}\n  is not an image. It starts: {head!r}")

        path = os.path.join(ROOT, target)
        os.makedirs(os.path.dirname(path), exist_ok=True)
        # Whole, then moved into place: an interrupted write must not leave a truncated
        # file that the next run skips as done.
        with open(path + ".part", "wb") as f:
            f.write(data)
        os.replace(path + ".part", path)
        print(f"  {index:3}/{len(missing)}  {target:56} {len(data) // 1024:5} KB", flush=True)

    print(f"\nfetched {len(missing)} pictures")
    return 0


if __name__ == "__main__":
    sys.exit(main())
